name: Deploy to Kubernetes

on:
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --file Dockerfile \
            --tag ideauxhub/hotel-fend:$GITHUB_RUN_NUMBER \
            --push .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Kubernetes
        uses: docker/k8s-deploy@main
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG_DATA }}
          images: ideauxhub/hotel-fend:$GITHUB_RUN_NUMBER
          imagePullSecrets: |
            [
              {
                "name": "regcred"
              }
            ]
          namespace: default
