name: Development

on:
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
           echo "BUILD_NUMBER=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ideauxhub/hotel-fend:$BUILD_NUMBER

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} 

      - name: Push the Docker image to Docker Hub
        run: docker push ideauxhub/hotel-fend:$BUILD_NUMBER

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up environment variables
        run: |
           echo "BUILD_NUMBER=$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

      - name: Install Ansible
        run: |
          sudo apt-get update
          sudo apt-get install software-properties-common
          sudo apt-add-repository --yes --update ppa:ansible/ansible
          sudo apt-get install ansible

      - name: Deploy using Ansible
        run: |
          ansible-playbook -i inventory/hosts deploy.yml --extra-vars "build_number=$BUILD_NUMBER"
